version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      - dependency-type: direct
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      official-github-actions:
        patterns:
          - 'actions/*'
      third-party-actions:
        patterns:
          - '*'
        exclude-patterns:
          - 'actions/*'
