name: Auto Translate

on:
  workflow_call:
    inputs:
      text_domain:
        description: 'Text domain for translation'
        required: true
        type: string

    secrets:
      TRANSLATOR_API_KEY:
        required: true
      NEWFOLD_ACCESS_TOKEN:
        required: true

permissions: {}

jobs:
  auto-translate:
    name: Auto-Translate and Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install requests polib

      - name: Set branch name
        id: vars
        run: echo "BRANCH=auto/translated-$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Download translate.py from parent repo
        run: |
          mkdir -p .github/scripts
          curl -H "Authorization: token ${{ secrets.NEWFOLD_ACCESS_TOKEN }}" \
              -H "Accept: application/vnd.github.v3.raw" \
              -o .github/scripts/translate.py \
              https://api.github.com/repos/newfold-labs/workflows/contents/.github/scripts/translate.py?ref=main

      - name: Translate PO and JSON files
        env:
          TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
          TEXT_DOMAIN: ${{ inputs.text_domain }}
        run: python .github/scripts/translate.py

      - name: Remove downloaded translate script
        run: rm .github/scripts/translate.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
          commit-message: Auto-translated PO and JSON files
          branch: ${{ steps.vars.outputs.BRANCH }}
          title: Auto-translated files update
          body: |
            This PR contains automatic translations of PO and JSON files.
          labels: translations
