name: Auto Translate

on:
  workflow_call:
    inputs:
      text_domain:
        description: 'Text domain for translation'
        required: true
        type: string

    secrets:
      TRANSLATOR_API_KEY:
        required: true
      NEWFOLD_ACCESS_TOKEN:
        required: true

permissions: {}

jobs:
  auto-translate:
    name: Auto-Translate and Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: 'Check for existing translations PR and exit if found'
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
        run: |
          prs=$(gh pr list --state open --label 'translations' --json number --jq '.[].number')
          if [ -n "$prs" ]; then
            echo 'A PR with "translations" label already exists:'
            echo "$prs"
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo 'No existing "translations" PR found. Continuing workflow.'
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check_pr.outputs.found == 'false'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        if: steps.check_pr.outputs.found == 'false'
        run: |
          pip install requests polib

      - name: Set branch name
        if: steps.check_pr.outputs.found == 'false'
        id: vars
        run: echo "BRANCH=auto/translated-$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Download translate.py from parent repo
        if: steps.check_pr.outputs.found == 'false'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
              repository: 'newfold-labs/workflows'
              path: 'translation-action-scripts'
              sparse-checkout: '.github/scripts/translate.py'
              sparse-checkout-cone-mode: false
              persist-credentials: false

      - name: Translate PO and JSON files
        if: steps.check_pr.outputs.found == 'false'
        env:
          TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
          TEXT_DOMAIN: ${{ inputs.text_domain }}
        run: python translation-action-scripts/.github/scripts/translate.py

      - name: Remove downloaded translate script
        if: steps.check_pr.outputs.found == 'false'
        run: rm translation-action-scripts

      - name: Create Pull Request
        if: steps.check_pr.outputs.found == 'false'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
          commit-message: Auto-translated PO and JSON files
          branch: ${{ steps.vars.outputs.BRANCH }}
          title: Auto-translated files update
          body: |
            This PR contains automatic translations of PO and JSON files.
          labels: translations
