name: Reusable Image Optimization

on:
  workflow_call:
    inputs:
      trigger-event:
        description: 'The event that triggered the workflow'
        required: true
        type: string
jobs:
  optimize-images:
    name: Optimize Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Sanitize Git credentials
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true

      - name: Image Optimization
        if: inputs.trigger-event == 'pull_request'
        id: image_optimization
        env:
          GITHUB_EVENT_NAME: ${{ inputs.trigger-event }}
        uses: calibreapp/image-actions@f32575787d333b0579f0b7d506ff03be63a669d1 # v1.4.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          compressOnly: false
          jpegQuality: '82'
          pngQuality: '82'
          webpQuality: '86'

      - name: Create Pull Request
        if: inputs.trigger-event == 'push' && steps.image_optimization.outputs.markdown != ''
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ github.token }}
          commit-message: 'Optimize images'
          title: 'Optimize images'
          body: |
            This PR contains optimized images with the following quality settings:
            - JPEG: 82% quality
            - PNG: 82% quality
            - WebP: 86% quality

            These settings follow WordPress Core standards for optimal balance between file size and visual quality.

            ${{ steps.image_optimization.outputs.markdown }}
          branch: image-optimization-${{ github.sha }}
          delete-branch: true
