name: Reusable Azure AI Translations

on:
  workflow_call:
    inputs:
      text_domain:
        description: 'Text domain for translation'
        required: true
        type: string

    secrets:
      TRANSLATOR_API_KEY:
        required: true

permissions: {}

jobs:
  auto-translate:
    name: Auto-Translate and Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: true

      - name: Check for existing translations PR and exit if found
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --label 'translations' --json number --jq '.[].number')
          if [ -n "$prs" ]; then
            echo 'A PR with "translations" label already exists:'
            echo "$prs"
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo 'No existing "translations" PR found. Continuing workflow.'
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        if: steps.check_pr.outputs.found == 'false'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        if: steps.check_pr.outputs.found == 'false'
        run: |
          pip install requests polib

      - name: Set branch name
        if: steps.check_pr.outputs.found == 'false'
        id: set_branch_name
        run: echo "BRANCH=auto-translate/${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

      - name: Download translate.py from parent repo
        if: steps.check_pr.outputs.found == 'false'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: 'newfold-labs/workflows'
          path: 'translation-action-scripts'
          sparse-checkout: '.github/scripts/translate.py'
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Translate PO and JSON files
        if: steps.check_pr.outputs.found == 'false'
        env:
          TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
          TEXT_DOMAIN: ${{ inputs.text_domain }}
        run: python translation-action-scripts/.github/scripts/translate.py

      - name: Remove downloaded translate script
        if: steps.check_pr.outputs.found == 'false'
        run: rm -rf translation-action-scripts

      - name: Configure Git identity
        if: steps.check_pr.outputs.found == 'false'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or reset to branch
        if: steps.check_pr.outputs.found == 'false'
        env:
          BRANCH_NAME: ${{ steps.set_branch_name.outputs.BRANCH }}
        run: |
          git checkout -B "$BRANCH_NAME"

      - name: Stage changes
        if: steps.check_pr.outputs.found == 'false'
        run: git add .

      - name: Commit changes
        if: steps.check_pr.outputs.found == 'false'
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping PR creation."
            exit 0
          fi
          git commit -m "Auto-translated PO and JSON files"

      - name: Push changes
        if: steps.check_pr.outputs.found == 'false'
        env:
          BRANCH_NAME: ${{ steps.set_branch_name.outputs.BRANCH }}
        run: |
          git push --force origin "$BRANCH_NAME"

      - name: Create Pull Request
        if: steps.check_pr.outputs.found == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.set_branch_name.outputs.BRANCH }}
        run: |
          PR_BODY="$({
            echo "This pull request contains automatic translations of PO and JSON files."
            echo ""
            echo "The workflow run responsible for creating this pull request can be found [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          })"

          gh pr create \
            --title "Updating translation files" \
            --body "$PR_BODY" \
            --base "${{ github.ref_name }}" \
            --head "$BRANCH_NAME" \
            --label "translations"
